### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by athulkrishna2015** [m4mallu/uniquify#12]
after running main.py 
iam getting this errror

...
 File "/home/admin/Downloads/uniquify/config.py", line 20, in Config
    APP_ID = int(os.environ.get("1123451", ""))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by m4mallu** [comment]
Simple python errors won't be addressed here.
