### ISSUE TITLE
I encountered an error

### ISSUE THREAD

**Issue by tissole** [m4mallu/uniquify#2]
I'm glad that I found this program, which is exactly what I need to clear my cluttered channel. I installed this on Windows 10, followed all the steps but when I run "py main.py"  I get this error:
https://nekobin.com/waguyozefi

How to fix it?

`

**Comment by m4mallu** [comment]
Check the variables given, check all the dependencies were satisfied, and try again. Code has no breaking bugs. !

**Comment by tissole** [comment]
Thanks for the feedback! After carefully checking I found the error source. I didn't generate a new session string, I just used one generated before by another app. Now I created a new one and everything is working fine. The old string was generated by a Telethon app and I see that this is generated by a Pyrogram based app. So maybe there are different formats.
